version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: kanvaro-postgres
    environment:
      POSTGRES_DB: kanvaro
      POSTGRES_USER: kanvaro
      POSTGRES_PASSWORD: Kanvaro@2025
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kanvaro -d kanvaro"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: kanvaro-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API Server
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: kanvaro-api
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://kanvaro:Kanvaro%402025@postgres:5432/kanvaro?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FRONTEND_URL: http://localhost:3000
      API_URL: http://localhost:3001
      JWT_SECRET: dev-secret-key
      SESSION_SECRET: dev-session-secret
      CSRF_SECRET: dev-csrf-secret
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    command: npm run start:dev

  # Web Application
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: kanvaro-web
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./apps/web:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

  # Database Management
  db-studio:
    image: node:18-alpine
    container_name: kanvaro-db-studio
    working_dir: /app
    environment:
      DATABASE_URL: postgresql://kanvaro:kanvaro@postgres:5432/kanvaro?schema=public
    volumes:
      - ./apps/api:/app
    command: npx prisma studio --hostname 0.0.0.0
    ports:
      - "5555:5555"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
